#!/bin/bash
name=lustre-demo
pool=$PWD/pool

if [ ! -f $PWD/pool/README.md ]; then
  echo "Please run $0 in the git repository directory."
  exit 1
fi

echo "Creating fast disks"
for disk in vd{b..e}; do
  truncate $pool/$name-fast-$disk.img -s 25G
  virsh --quiet attach-disk $name-mds0 $pool/$name-fast-$disk.img --persistent --shareable --type disk --cache none --target $disk
  virsh --quiet attach-disk $name-mds1 $pool/$name-fast-$disk.img --persistent --shareable --type disk --cache none --target $disk
  virsh blkdeviotune $name-mds0 $disk --total-iops-sec 200 --total-bytes-sec 50M --config
  virsh blkdeviotune $name-mds1 $disk --total-iops-sec 200 --total-bytes-sec 50M --config
done

echo "Creating slow disks"
for disk in vd{b..g}; do
  truncate $pool/$name-slow-$disk.img -s 50G
  virsh --quiet attach-disk $name-oss0 $pool/$name-slow-$disk.img --persistent --shareable --type disk --cache none --target $disk
  virsh --quiet attach-disk $name-oss1 $pool/$name-slow-$disk.img --persistent --shareable --type disk --cache none --target $disk
  virsh blkdeviotune $name-oss0 $disk --total-iops-sec 50 --total-bytes-sec 10M --config
  virsh blkdeviotune $name-oss1 $disk --total-iops-sec 50 --total-bytes-sec 10M --config
done

