#!/bin/bash
pool=lustre-demo
echo "Creating pool $pool in $PWD"

virsh pool-create-as --name $pool --type dir --target $PWD

echo "Creating SSD MDT disks"
for disk in SSD{0..5}; do virsh vol-create-as --name $disk --pool $pool --format qcow2 --capacity 25G; done

echo "Creating HDD OST disks"
for disk in HDD{0..7}; do virsh vol-create-as --name $disk --pool $pool --format qcow2 --capacity 50G; done

