#!/bin/bash

prefix=234
name=lustre-demo
pool=$PWD/pool


setup-network() {
  echo "Setup network $name-$prefix"

cat > libvirt/network-$prefix.xml << EOF
<network>
  <name>lustre-demo-$prefix</name>
  <forward mode='nat'>
    <nat>
      <port start='1024' end='65535'/>
    </nat>
  </forward>
  <bridge name='virbr$prefix' stp='on' delay='0'/>
  <domain name='local' localOnly='yes'/>
  <ip address='192.168.$prefix.1' netmask='255.255.255.0'>
    <dhcp>
      <range start='192.168.$prefix.2' end='192.168.$prefix.254'/>
      <host mac='52:54:00:a7:29:6c' name='$name-mds0' ip='192.168.$prefix.10'/>
      <host mac='52:54:00:e5:b1:6a' name='$name-mds1' ip='192.168.$prefix.11'/>
      <host mac='52:54:00:0e:8d:29' name='$name-oss0' ip='192.168.$prefix.20'/>
      <host mac='52:54:00:85:f0:ae' name='$name-oss1' ip='192.168.$prefix.21'/>
      <host mac='52:54:00:f9:c2:18' name='$name-client' ip='192.168.$prefix.2'/>
    </dhcp>
  </ip>
</network>
EOF
  virsh --quiet net-define libvirt/network-$prefix.xml
}

setup-guest() {
  echo "Setup VM $name-$1"
  virsh --quiet define libvirt/lustre-demo-$1.xml
  [ -f $pool/$name-$1.qcow2 ] || ( cd $pool && qemu-img create -q -f qcow2 -F qcow2 -b lustre-demo-orig.qcow2 $name-$1.qcow2 )
  virsh --quiet attach-disk $name-$1 $pool/$name-$1.qcow2 --persistent --type disk --target vda --driver qemu --subdriver qcow2
}


download-image() {
orig=lustre-demo-orig.qcow2
  if [ -f $pool/$orig ] && [ $(stat -c %s $pool/$orig) = 2098331648 ]; then
    echo "Demo VM $orig already downloaded"
  else
    echo "Downloading lustre-demo Almalinux 8 Linux image..."
    ( cd $pool && wget --continue https://www.cs.helsinki.fi/u/jjaakkol/lustre-demo-orig.qcow2 ) || exit 1
  fi
}


create() {
  download-image
  setup-network
  for guest in client mds0 mds1 oss0 oss1; do
    setup-guest $guest
  done
}


stop() {
  for guest in client mds0 mds1 oss0 oss1; do
    virsh --quiet destroy $name-$guest
  done
  virsh --quiet net-destroy lustre-demo-$prefix
  echo "VMs and networks stopped"
}     

destroy() {
  for guest in client mds0 mds1 oss0 oss1; do
    rm -vf $pool/$name-$guest.qcow2
  done
  virsh --quiet net-undefine lustre-demo-$prefix
  echo "VMs and networks destroyed"
}     

start() {
  echo "Starting network lustre-demo-$prefix"
  virsh --quiet net-start lustre-demo-$prefix
  echo "Starting guests" 
  for guest in client mds0 mds1 oss0 oss1; do
    virsh --quiet start $name-$guest
  done
  while read ip name; do
    echo "Waiting for $name at $ip to come up"
    while ! ping -c 1 -W 1 $ip  > /dev/null; do
      echo -n "."
    done
    sleep 1
    ssh -i ./id_rsa root@$ip "echo Configuring $ip; cd /root/lustre-demo && { git pull -q && ./configure-guest.sh $name ;}" < /dev/null

  done < vm-hosts
}

case $1 in
start)
        start
        ;;
stop)
        stop
        ;;
create)
        create
        ;;
destroy)
        destroy
        ;;
*)
        cat << EOF
Usage:
$0 start
$0 stop
$0 create
$0 destroy
EOF
esac


